version: '3.8'

services:
  anti-prompt-injection:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MAX_PROMPT_LENGTH=10000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
